### ISSUE TITLE
Entering ROM again -- impressions and thoughts

### ISSUE THREAD

**Issue by blelump** [rom-rb/rom-repository#81] opened 2017-03-13 16:50 UTC
Hello ! 

I'd like to share with you with my thoughts while exploring various ROM features. I'd be glad to help with the docs, but at first need to dig into it deeper.
* When you are a post AR guy and for any reason you've found ROM interesting, it will be diffcult to get on board quickly. Either you are familiar with the concepts of DDD and you know its tactical patterns or not, the ROM concepts should be easy to adopt for the rest of the world. It is likely at least half of the people looking at ROM are post AR folks so as an example, when you enter the [Active Record and ROM][1] of the learn section , you get the differences between AR and ROM, but you won't find any _cheatsheet_ of how to resolve this or that, the _implemenation details_. Well, this is actually a minor problem -- much more important is how to switch the mindset from the post AR world and get the things done. Actually here comes another question -- whether the ROM itself focuses to be the AR replacement or an alternative solution for building reliable business apps. The latter sounds more suitable -- at least for me -- but it also comes with a cost. In essence, to get deep understanding of why ROM is the most suitable solution around in an enterprise app, at least basic knowledge of DDD concepts is desired. If one comes without that, perhaps it would be good to explain that in the learn section. Something about one and a half year ago I was that guy and since then -- IMO -- the ROM concepts evaluated to even more complex solution. This is not a bad thing, not at all, but it also requires the knowledge of how to get things done. Here comes next bullet;
* The great number of possible solutions for one problem. 
  * Lets consider the concept of reading an aggregate. You can use `combine` method and its variations, you can use associations, you can use `aggregate` and as the learn section [says][2] you can use the `wrap_parent` method. Huh, a lot of that. These below produce the same result:

    ```
    p tag_repo.tags.combine(:taggables).to_a
    p tag_repo.aggregate(:taggables).to_a
    p tag_repo.tags.wrap_parent(taggable: tag_repo.taggables).to_a

    => [
      #<ROM::Struct[Tag] id=1 taggable_id=1 name="red" taggables=#<ROM::Struct[Taggable] id=1 tag_id=1>>, 
      #<ROM::Struct[Tag] id=2 taggable_id=2 name="blue" taggables=#<ROM::Struct[Taggable] id=2 tag_id=2>>
    ]
    ``` 

    Uhm, actually the `tag_id` of `Taggable` is missing in the third approach, but the question remains -- which one should I use and why or in which case? What are the differences among them and why should I pick one over another?

    edit: it seems `wrap_parent` is preffered over `aggregate` , because it utilizes SQL `join` instead of loading each dependency as a separate SQL query. Can it be compared to the `#preload` vs `#eager_load` from the AR world ? 

  * Associations vs `relation.combine`. With my current understanding, you can achieve the same result with both approaches. What is the difference between them and why should I favor one approach over another?

  * `#combine` and `#wrap` methods and their variations. They seem to be very powerful tools and just a glance at the code convinces me that Piotr have had his hands in this as the code shines :wink: . However, what's the main purpose of using them (and what's the difference between them) . Going to the docs: 
  `#combine` -- Combine with other relations;
  `#wrap` -- Wrap other relations.

    Fine enough, but when should I use it? `# I've also seen the #node method and I am not sure as well when should I use it`

* Other ROM DSL doubts. 

  * [Projection DSL][3] -- what's that and when one should use it? As an example:
    ```
    p tag_repo.tags.select(:id, :name)
    => #<ROM::Relation[Tags] name=tags dataset=#<Sequel::SQLite::Dataset: "SELECT `id`, `name` FROM `tags` ORDER BY `tags`.`id`">>
    p tag_repo.tags.select { [id, name] }
    => #<ROM::Relation[Tags] name=tags dataset=#<Sequel::SQLite::Dataset: "SELECT `id`, `name` FROM `tags` ORDER BY `tags`.`id`">>
    p tag_repo.tags.select { [id.qualified, name.qualified] }
    => #<ROM::Relation[Tags] name=tags dataset=#<Sequel::SQLite::Dataset: "SELECT `tags`.`id`, `tags`.`name` FROM `tags` ORDER BY `tags`.`id`">>
    ```
   
    Huh... May it be explained as an engine tailored to dealing with columns ? 

  * The [`#[]`][4] operator performed on `ROM::Repository` adds extra features to the child class. In particular I am able to do smth like:

    ```
    class TagRepo < ROM::Repository::Root
      root :tags
      relations :taggables, :tags
    end
    ```

    and then `tag_repo.root.combine(:taggables).to_a` or `tag_repo.aggregate(:taggables).to_a`. If the root relation is `tags` -- perhaps my deduction is wrong -- then why select is the opposite:

    ```
    SELECT `taggables`.`id`, `tags`.`id` AS 'tag_id' FROM `taggables` INNER JOIN `tags` ON (`tags`.`taggable_id` = `taggables`.`id`) WHERE (`tags`.`id` IN (1, 2)) ORDER BY `taggables`.`id`
    ```

A lot of that, but my intention is to grasp the idea as a whole and as I said at the beginning, contribute to the Learn section. In particular I think something like [this][5] is quite unachievable now, but the API basics exposed similarly to what is shown [here][6] (with the idea of examples at least for all the methods from `Repository::RelationProxy`) would be a good start.

ps. Even though I don't understand all the concepts or their solutions -- yet -- the library itself is the most complex and powerful engine I've seen in the terms of dealing with various persistence layers. :heart: 

[1]: http://rom-rb.org/learn/introduction/active-record/
[2]: http://rom-rb.org/learn/repositories/reading-aggregates/
[3]: http://rom-rb.org/learn/sql/queries/
[4]: https://github.com/rom-rb/rom-repository/blob/master/lib/rom/repository/class_interface.rb#L19
[5]: http://guides.rubyonrails.org/association_basics.html
[6]: http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html

**Comment by flash-gordon** [comment] 2017-03-13 19:03
@solnic will definitely write more on this but I want to stress that most of the things you mentioned are just low-level vs high-level API. E.g. you can use associations for combining when the underlying relations _have_ them. Another good example is changesets which based on commands, but they're more high-level. The docs should probably start with the highest level and drill down to the low-level stuff describing relations between components.


Regarding `Root` relation
```sql
SELECT `taggables`.`id`, `tags`.`id` AS 'tag_id' FROM `taggables` INNER JOIN `tags` ON (`tags`.`taggable_id` = `taggables`.`id`) WHERE (`tags`.`id` IN (1, 2)) ORDER BY `taggables`.`id`
```
This query fetches the records from `taggables` _after_ the records from `tags` have been fetched. After that ROM will _combine_ the results.

Regarding `ProjectionDSL`, you're using it when you want to select something not trivial, like get a SQL function value or things like that:

```ruby
    relations[:users]
	      .inner_join(:tasks, user_id: :id)
	      .qualified
	      .select_group(:id, :name)
	      .select_append { int::count(:tasks).as(:task_count) }
```

```ruby
relation.select { `'event'`.as(:type) } # selecting SQL string
```

**Comment by blelump** [comment] 2017-03-15 19:16
Hello @flash-gordon and thanks for answering!

> @solnic will definitely write more on this but I want to stress that most of the things you mentioned are just low-level vs high-level API. E.g. you can use associations for combining when the underlying relations have them. Another good example is changesets which based on commands, but they're more high-level. The docs should probably start with the highest level and drill down to the low-level stuff describing relations between components.

So far I am exploring the reading side, but indeed the _changesets_ example is a good point of having associations defined within relations. However, lets assume that I'm having a reporting engine and I utilize queries only. I have two levels of API's (the lower and higher) and since they both are public, the author intention was to use them both, but in what cases? :wink: `# sure we can wait for Piotr's answer`.

In an enterprise app I can imagine a bunch of associations defined within one relation and perhaps the _associations approach_ is more explicit (since you literally can see to which other relations this relation talks to), whereas the `#combine`, `#wrap` approach is more implicit? Nontheless it's still unclear to me. 

Regarding `root` relation that's true. The query as a whole looks like:
```
SELECT `id`, `taggable_id`, `name` FROM `tags` ORDER BY `tags`.`id`
SELECT `taggables`.`id`, `tags`.`id` AS 'tag_id' FROM `taggables` INNER JOIN `tags` ON (`tags`.`taggable_id` = `taggables`.`id`) WHERE (`tags`.`id` IN (1, 2)) ORDER BY `taggables`.`id`
```
so tags are fetched first.

Finally, thanks for `ProjectionDSL` explanation!

**Comment by solnic** [comment] 2017-06-21 18:29
Sorry for late reply, I didn't forget as you can see. Thanks for great feedback, luckily I was aware of the many points you've made and our effort with rom 4.0 addresses your concerns. The way things are in rom 3.0 is mostly because repository was added as a semi-experiment to see how far we can go with automation, and it turned out we can go pretty damn far. So we've done this now with rom 4.0 where most advanced functionality of rom-repository was ported right into core API. This means that we can finally represent Relation API as a coherent set of features, without making distinction between what's possible with relations vs repos and their relations. This will make usage much simpler. Furthermore we made associations available *to all adapters*, which means `combine` and `wrap` works *only when associations are defined* and you can't use them to compose relations in an arbitrary way. You can still compose relations into graphs however you want but it's pretty clear it's a low level API, using different method names and it's much much simpler than `combine` known from rom 3.x / repo 1.x, and I don't expect people to use it, except some very rare cases.

When it comes to `combine` and `wrap` these are just two different concepts to learn and remember. `combine` is used to produce a graph with a root relation and its nodes, where all those relations will be materialized separately and merged into a single result. This means a database will be queried multiple times. Now wrap is very similar, as it's also a graph with root and nodes, but some backends allow you to fetch all data with a single call. You can do this with SQL via join, and you can do this with various JSON HTTP APIs too. We can't automatically figure out which strategy is better, hence the use must a) know about the two approaches b) be able to decide which one works better in a particular use case. Fun fact - initially `wrap` was faster in many cases than `combine` in SQL, but then the underlying data transformation function was refactored *so well* that `combine` is now slightly faster :)

As far as projection DSL in rom-sql goes, this is, in other words, just a query DSL, and it's probably the most powerful query DSL that exists in Ruby. The reason why we focused so much on making it so advanced is because rom-rb favors database features, there's a lot you can achieve using your database so that your application code will be simpler.

...and in general, rom-rb is not and will not be a replacement for ActiveRecord, the two libs are completely different. This is a true alternative to how you work with data in Ruby, regardless of the database. I wouldn't even say that you need to be familiar with DDD, personally I've never applied much of DDD to my code and for me it's not really a 100% good fit. I know we have repos and aggregates but it's not really DDD. I'm sure you could apply full-blown DDD with rom-rb with way less effort than with AR, FWIW, but I wouldn't say it's a requirement to understand rom-rb.

At the end of the day I feel like doubts, concerns and problems with understanding rom-rb have been always caused by the fact this library is built bottom-up with some level of experimentation as intermediate steps. Fortunately this era in the project history is about to end along with rom 4.0, so please check it out once it's released.

**Closed as completed** 2017-06-22 05:54 UTC

**Comment by blelump** [comment] 2017-06-22 14:10
Cześć @solnic !

Thanks for your answer and feedback. I must admit, I haven't touched ROM since then, but I'll definitely try the 4.0 version once it's released !
